# chris.p.tang@gmail.com

version: '3'

services:
  v2ray:
    image: chrisptang/v2ray:latest
    container_name: v2ray
    restart: always
    environment:
      - NEW_UUID=${NEW_UUID}
    volumes: 
      - ./v2ray_logs:/var/log/v2ray
    ports:
      - "32000:32000"